"""Add title to visualization

Revision ID: 824a7bc2f076
Revises: 299f22992903
Create Date: 2017-03-06 15:25:48.415065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '824a7bc2f076'
down_revision = '299f22992903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visualization', sa.Column('title', sa.String(length=200), nullable=False, 
        server_default=''))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visualization', 'title')
    # ### end Alembic commands ###
