"""Add title to visualization

Revision ID: 824a7bc2f076
Revises: 299f22992903
Create Date: 2017-03-06 15:25:48.415065

"""
from alembic import op
import sqlalchemy as sa
from caipirinha.migration_utils import is_sqlite


# revision identifiers, used by Alembic.
revision = '824a7bc2f076'
down_revision = '299f22992903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visualization', sa.Column('title', sa.String(length=200), nullable=False, 
        server_default=''))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if is_sqlite():
        with op.batch_alter_table('visualization') as batch_op:
            batch_op.drop_column('title')
    else:
        op.drop_column('visualization', 'title')
    # ### end Alembic commands ###
