"""Dashboard improvements

Revision ID: b3d0713c453e
Revises: 13b676178b08
Create Date: 2020-04-20 15:42:51.203275

"""
from alembic import op
from sqlalchemy import String, Integer
from sqlalchemy.sql import table, column, text


# revision identifiers, used by Alembic.
revision = 'b3d0713c453e'
down_revision = '13b676178b08'
branch_labels = None
depends_on = None

def insert_visualization_type():
    tb = table(
        'visualization_type',
        column('id', Integer),
        column('name', String),
        column('help', String),
        column('icon', String))

    all_ops = [
        (72, 'markdown', 'Markdown text', 'fa-text'),
    ]
    rows = [dict(zip([c.name for c in tb.columns], operation)) for operation in
            all_ops]

    op.bulk_insert(tb, rows)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.execute(text('START TRANSACTION'))
        insert_visualization_type()
        op.execute(text('COMMIT'))
    except:
        op.execute(text('ROLLBACK'))
        raise


# noinspection PyBroadException
def downgrade():
    try:
        op.execute(text('START TRANSACTION'))
        op.execute(text("DELETE FROM visualization_type WHERE id IN (72)"))
        op.execute(text('COMMIT'))
    except:
        op.execute(text('ROLLBACK'))
        r
