"""empty message

Revision ID: cfacecb61ac1
Revises: ed3b7980089f
Create Date: 2017-08-29 16:04:04.529943

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql
from sqlalchemy.sql import text
from caipirinha.migration_utils import is_sqlite

# revision identifiers, used by Alembic.
revision = 'cfacecb61ac1'
down_revision = 'ed3b7980089f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.engine.name == 'mysql':
        op.add_column('dashboard',
                  sa.Column('configuration', mysql.LONGTEXT(), nullable=True))
    else:
        op.add_column('dashboard',
                  sa.Column('configuration', sa.Text(), nullable=True))

    op.add_column('dashboard',
                  sa.Column('is_public', sa.Boolean(),
                            default=True,
                            server_default='0',
                            nullable=False))
    op.execute(text(
        "UPDATE visualization_type SET name = 'scatter-plot' WHERE id =87"
    ))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if is_sqlite():
        with op.batch_alter_table('dashboard') as batch_op:
            batch_op.drop_column('is_public')
            batch_op.drop_column('configuration')
    else:
        op.drop_column('dashboard', 'is_public')
        op.drop_column('dashboard', 'configuration')

    op.execute(text(
            "UPDATE visualization_type SET name = 'plot-chart' WHERE id =87"
    ))
