"""empty message

Revision ID: cfacecb61ac1
Revises: ed3b7980089f
Create Date: 2017-08-29 16:04:04.529943

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'cfacecb61ac1'
down_revision = 'ed3b7980089f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard',
                  sa.Column('configuration', sa.Text(), nullable=True))
    op.add_column('dashboard',
                  sa.Column('is_public', sa.Boolean(),
                            default=True,
                            nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboard', 'is_public')
    op.drop_column('dashboard', 'configuration')
    # ### end Alembic commands ###
