"""Fill visualization type table

Revision ID: d5ce40ba77de
Revises: 824a7bc2f076
Create Date: 2017-06-02 14:57:57.149575

"""

from alembic import op
from sqlalchemy import String, Integer
from sqlalchemy.sql import table, column, text

# revision identifiers, used by Alembic.
revision = 'd5ce40ba77de'
down_revision = '824a7bc2f076'
branch_labels = None
depends_on = None


def insert_visualization_type():
    tb = table(
        'visualization_type',
        column('id', Integer),
        column('name', String),
        column('help', String),
        column('icon', String))

    all_ops = [
        (1, 'html', 'Html', 'fa-bullseye'),
        (19, 'evaluate-model', 'Evaluate Model', 'fa-check'),
        (35, 'table-visualization', 'Table Visualization', 'fa-table'),
        (68, 'line-chart', 'Line, Chart', 'fa-line-chart'),
        (69, 'bar-chart', 'Bar Chart', 'fa-bar-chart'),
        (70, 'pie-chart', 'Pie Chart', 'fa-pie-chart'),
        (80, 'scatter-plot', 'Scatter plot', 'fa-square'),
        (81, 'summary-statistics', 'Summary statistics', 'fa-calculator'),
    ]
    rows = [dict(zip([c.name for c in tb.columns], operation)) for operation in
            all_ops]

    op.bulk_insert(tb, rows)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.execute(text('START TRANSACTION'))
        insert_visualization_type()
        op.execute(text('COMMIT'))
    except:
        op.execute(text('ROLLBACK'))
        raise


# noinspection PyBroadException
def downgrade():
    try:
        op.execute(text('START TRANSACTION'))
        op.execute(text("DELETE FROM visualization_type"))
        op.execute(text('COMMIT'))
    except:
        op.execute(text('ROLLBACK'))
        raise
