"""Add new fields

Revision ID: d73f1a3bccf3
Revises: b3d0713c453e
Create Date: 2020-04-20 15:55:00.951631

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd73f1a3bccf3'
down_revision = 'b3d0713c453e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard', sa.Column('hash', sa.String(length=200), nullable=True))
    op.add_column('visualization', sa.Column('workflow_id', sa.Integer(), nullable=True))
    op.alter_column('visualization', 'job_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('visualization', 'suggested_width',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('visualization', 'task_id',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visualization', 'task_id',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=200),
               nullable=False)
    op.alter_column('visualization', 'job_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('visualization', 'suggested_width',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('visualization', 'workflow_id')
    op.drop_column('dashboard', 'hash')
    # ### end Alembic commands ###
